@PJAKT_APBD_Cw8_HostAddress = http://localhost:5123

### 1. Pobierz wszystkich pacjentów (Zadanie 2)
GET {{PJAKT_APBD_Cw8_HostAddress}}/api/patients
Accept: application/json

### 2. Pobierz pacjentów przefiltrowanych po nazwisku (Zadanie 2 - "Kowalski")
GET {{PJAKT_APBD_Cw8_HostAddress}}/api/patients?search=Kowalski
Accept: application/json

### 3. Pobierz pacjentów z fragmentem (Zadanie 2 - "an")
GET {{PJAKT_APBD_Cw8_HostAddress}}/api/patients?search=an
Accept: application/json

### 4. Przypisanie łóżka pacjentowi (Zadanie 3 - Przykład 1)
POST {{PJAKT_APBD_Cw8_HostAddress}}/api/patients/90010112345/bedassignments
Content-Type: application/json

{
  "from": "2026-05-20T14:00:00",
  "to": "2026-05-30T10:00:00",
  "bedType": "Standard",
  "ward": "Kardiologia"
}

### 5. Przypisanie łóżka bez daty końcowej (Zadanie 3 - Przykład 2)
POST {{PJAKT_APBD_Cw8_HostAddress}}/api/patients/85050567890/bedassignments
Content-Type: application/json

{
  "from": "2026-06-01T09:00:00",
  "bedType": "Intensywna terapia",
  "ward": "Chirurgia"
}